<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>isegoria_wpf</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>isegoria_icon.ico</ApplicationIcon>
    <PackageIcon>isegoria_icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\IrishGrover-Regular.ttf" />
    <None Remove="Assets\Fonts\PretendardVariable.ttf" />
    <None Remove="Assets\isegoria_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\IrishGrover-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="isegoria_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Downloads\isegoria_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\PretendardVariable.ttf" />
    <Resource Include="Assets\isegoria_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
