<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>isegoria_wpf</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>isegoria_icon.ico</ApplicationIcon>
    <PackageIcon>isegoria_icon.png</PackageIcon>
   <AssemblyName>Isegoria</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\add_circle_icon.png" />
    <None Remove="Assets\add_icon.png" />
    <None Remove="Assets\arrow_left_icon.png" />
    <None Remove="Assets\arrow_right_icon.png" />
    <None Remove="Assets\call_slash_icon.png" />
    <None Remove="Assets\chat_icon.png" />
    <None Remove="Assets\close-circle.png" />
    <None Remove="Assets\close_icon.png" />
    <None Remove="Assets\Fonts\IrishGrover-Regular.ttf" />
    <None Remove="Assets\Fonts\PretendardVariable.ttf" />
    <None Remove="Assets\img_add_icon.png" />
    <None Remove="Assets\isegoria_icon.png" />
    <None Remove="Assets\mic_icon.png" />
    <None Remove="Assets\mic_mute_icon.png" />
    <None Remove="Assets\minimized_icon.png" />
    <None Remove="Assets\search_icon.png" />
    <None Remove="Assets\send_icon.png" />
    <None Remove="Assets\setting_icon.png" />
    <None Remove="Assets\user_edit_icon.png" />
    <None Remove="Assets\voice_icon.png" />
    <None Remove="Assets\voice_mute_icon.png" />
    <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\add_circle_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\add_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\arrow_left_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\arrow_right_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\call_slash_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\chat_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\close-circle.png" />
    <Resource Include="Assets\close_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\default_profile.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\IrishGrover-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="isegoria_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Downloads\isegoria_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="CredentialManagement" Version="1.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\PretendardVariable.ttf" />
    <Resource Include="Assets\img_add_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\isegoria_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\mic_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\mic_mute_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\minimized_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\search_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\send_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\setting_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\user_edit_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\voice_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\voice_mute_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
